services:
  frontend:
    build: .
    container_name: fansbetliga_app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - php

  php:
    image: php:8.2-apache
    container_name: fbl-php
    ports:
      - "8080:80"           # API at http://localhost:8080
    volumes:
      - .:/var/www/html     # serve your project root
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    restart: unless-stopped








