(function () {
  const STORAGE_KEY = "FBL_LANG";
  const DEFAULT_LANG = "en";

  // ✅ Your dictionary (add more keys anytime)
  const DICT = {
    fr: {
      // ===== existing =====

      // --- COMMON (missing keys you saw on Predictions) ---
      "common.matches": "Matchs",
      "common.done": "Terminé",
      "common.cancel": "Annuler",
      "common.confirm": "Confirmer",
      "common.prevAria": "Précédent",
      "common.nextAria": "Suivant",
      "common.closeAria": "Fermer",
      "common.betPlus": "Pronostics +",
      "common.about": "À propos",
      "common.pointsLabel": "Points :",

      // --- RESULTS (generated by resultsPage.js) ---
      "league.laliga": "La Liga",
      "league.bundesliga": "Bundesliga",
      "league.premier": "Premier League",
      "league.afcon": "Afcon",
      "results.seasonTitle": "Saison 2025 - 2026",
      "results.pointsLabel": "Points:",
      "results.guest": "Invité",
      "results.match": "MATCH",
      "results.yourPrediction": "Votre pronostic",
      "results.finalScore": "Score final",
      "results.noPredictions": "Aucun pronostic pour {league} pour le moment.",
      "results.noResultsYet": "Aucun résultat pour le moment.",

      // --- PREDICTIONS (generated by predictionsPage.js) ---
      "predictions.leagueMatches": "Matchs {league}",
      "predictions.matchdayOf": "Journée {n} sur {total}",
      "predictions.ofTotalShort": "{n} sur {total}",
      "predictions.confirmTitle":
        "Voulez-vous vraiment envoyer ces scores ? Veuillez confirmer que toutes les informations sont correctes.",
      "predictions.enterPredictionScore": "Entrez votre score de pronostic",
      "predictions.matchdayWord": "Journée",
      "predictions.groupHeader": "{group} - Journée {n}",

      // (Keep your old flat keys too in case some pages still use them)
      matches: "Matchs",
      done: "Terminé",
      cancel: "Annuler",
      confirm: "Confirmer",
      prevAria: "Précédent",
      nextAria: "Suivant",
      closeAria: "Fermer",
      leagueMatches: "Matchs {league}",
      matchdayOf: "Journée {n} sur {total}",
      ofTotalShort: "{n} sur {total}",
      confirmTitle:
        "Voulez-vous vraiment envoyer ces scores ? Veuillez confirmer que toutes les informations sont correctes.",
      enterPredictionScore: "Entrez votre score de pronostic",
      matchdayWord: "Journée",
      groupHeader: "{group} - Journée {n}",

      // ===== existing =====
      app_name: "FANSBETLIGA",
      about: "À propos",
      wallet: "Portefeuille",
      notifications: "Notifications",
      login: "Connexion",
      signup: "Inscription",
      email: "Email",
      password: "Mot de passe",
      confirm_password: "Confirmer le mot de passe",
      start: "Commencer",
      bet_plus: "Ponostiq",
      add_money: "Ajouter de l'argent",
      withdraw_funds: "Retirer des fonds",
      recent_transactions: "Transactions récentes",
      view_all: "Tout voir",
      current_balance: "Solde courant",
      bonus_balance: "Solde bonus",
      language: "Langue",
      english: "Anglais",
      french: "Français",

      // ===== added (minimal) to match your CURRENT HTML keys =====
      "app.brand": "FANSBETLIGA",
      "nav.notificationsAria": "Notifications",
      "nav.notificationsAlt": "Notifications",

      "nav.home": "Accueil",
      "nav.results": "Résultats",
      "nav.winners": "Gagnants",
      "nav.rules": "Règles",

      "nav.notifications": "Notifications",
      "wallet.withdrawBonus": "Retirer le bonus",
      "wallet.wallet": "Portefeuille",

      "predictions.matchStartedMsg": "Match commencé",
      "predictions.matchPassedMsg": "Match terminé",
      "predictions.matchLockedSaveMsg": "Sauvegarde verrouillée",
      // AFCON groups
      "afcon.groupA.heading": "CAN 2025 — Groupe A",
      "afcon.groupB.heading": "CAN 2025 — Groupe B",
      "afcon.groupC.heading": "CAN 2025 — Groupe C",
      "afcon.groupD.heading": "CAN 2025 — Groupe D",
      "afcon.groupE.heading": "CAN 2025 — Groupe E",
      "afcon.groupF.heading": "CAN 2025 — Groupe F",

      "afcon.groupA.tab": "Groupe A",
      "afcon.groupB.tab": "Groupe B",
      "afcon.groupC.tab": "Groupe C",
      "afcon.groupD.tab": "Groupe D",
      "afcon.groupE.tab": "Groupe E",
      "afcon.groupF.tab": "Groupe F",

      "afcon.groupA.day1.date": "Dimache, 21 Déc 2025",
      "afcon.groupA.day2.date": "Vendredi, 26 Déc 2025",
      "afcon.groupA.day3.date": "Mardi, 29 Déc 2025",

      "afcon.groupB.day1.date": "Lundi, 22 Déc 2025",
      "afcon.groupB.day2.date": "Vendredi, 26 Déc 2025",
      "afcon.groupB.day3.date": "Lundi, 29 Déc 2025",

      "afcon.groupC.day1.date": "Mardi, 23 Déc 2025",
      "afcon.groupC.day2.date": "Samedi, 27 Déc 2025",
      "afcon.groupC.day3.date": "Mardi, 30 Déc 2025",

      "afcon.groupD.day1.date": "Mardi, 23 Déc 2025",
      "afcon.groupD.day2.date": "Samedi, 27 Déc 2025",
      "afcon.groupD.day3.date": "Mardi, 30 Déc 2025",

      "afcon.groupE.day1.date": "Mecredi, 24 Déc 2025",
      "afcon.groupE.day2.date": "Dimache, 28 Déc 2025",
      "afcon.groupE.day3.date": "Mercredi, 31 Déc 2025",

      "afcon.groupF.day1.date": "Mecredi, 24 Déc 2025",
      "afcon.groupF.day2.date": "Dimache, 28 Déc 2025",
      "afcon.groupF.day3.date": "Mercredi, 31 Déc 2025",

      // ✅ matchday headers MUST be FLAT keys (strings)
      "afcon.groupA.matchdayHeader": "Groupe A - Journée {n} sur {total}",
      "afcon.groupB.matchdayHeader": "Groupe B - Journée {n} sur {total}",
      "afcon.groupC.matchdayHeader": "Groupe C - Journée {n} sur {total}",
      "afcon.groupD.matchdayHeader": "Groupe D - Journée {n} sur {total}",
      "afcon.groupE.matchdayHeader": "Groupe E - Journée {n} sur {total}",
      "afcon.groupF.matchdayHeader": "Groupe F - Journée {n} sur {total}",

      // --- WINNERS (winners.html + winnersPage.js) ---
      "winners.preseasonTitle": "Pré-saison 2025 - 2026",
      "winners.classification": "CLASSEMENT",

      "winners.dailyRankings": "Classement journalier",
      "winners.firstRound": "1er tour",
      "winners.overall": "Général",

      "winners.loadingRankings": "Chargement du classement…",
      "winners.noRankingsYet": "Pas de classement pour l'instant.",
      "winners.noRankingsThisMatchday": "Pas de classement pour cette journée.",

      "winners.rank": "Rang",
      "winners.player": "Joueur",
      "winners.points": "Points",
      "winners.pointsCol": "Points",

      "winners.groupMatchdayLabel": "{group} · Journée {n}",

      // --- WALLET (wallet.html) ---
      "wallet.brand": "FansWallet",
      "wallet.currentBalance": "Solde courant",
      "wallet.bonusBalance": "Solde bonus",
      "wallet.quickActions": "Actions rapides",
      "wallet.addMoney": "Ajouter de l'argent",
      "wallet.withdrawFunds": "Retirer des fonds",
      "wallet.recentTransactions": "Transactions récentes",
      "wallet.viewAll": "Tout voir",
      "wallet.deposit": "Dépôt",
      "wallet.withdrawal": "Retrait",

      // Deposit modal
      "wallet.depositModal.title": "Faire un dépôt",
      "wallet.depositModal.aria": "Faire un dépôt",
      "wallet.provider.momo": "MTN Mobile Money",
      "wallet.provider.orange": "Orange Money",
      "wallet.amountLabel": "Montant (FCFA)",
      "wallet.amountPlaceholder": "ex. 5000",
      "wallet.phoneLabel": "Numéro de téléphone",
      "wallet.phonePlaceholder": "ex. 6XXXXXXXX",
      "wallet.depositBtn": "Dépôt",
      "wallet.cancelBtn": "Annuler",
      "wallet.depositNote":
        "Après confirmation, vous recevrez une demande de paiement sur votre téléphone.",

      // Withdraw modal
      "wallet.withdrawModal.title": "Retirer des fonds",
      "wallet.withdrawModal.aria": "Retirer des fonds",
      "wallet.withdrawBtn": "Retirer",
      "wallet.withdrawNote":
        "Les retraits peuvent prendre quelques minutes selon l’opérateur.",
      "wallet.closeAria": "Fermer",

      // ============================================================
      // ✅ ADDED NOW: AFCON teams (French + English)
      // Use in HTML/JS as: data-i18n="team.afcon.<slug>"
      // ============================================================

      "team.afcon.algeria": "Algérie",
      "team.afcon.angola": "Angola",
      "team.afcon.benin": "Bénin",
      "team.afcon.botswana": "Botswana",
      "team.afcon.burkinafaso": "Burkina Faso",
      "team.afcon.burundi": "Burundi",
      "team.afcon.cameroon": "Cameroun",
      "team.afcon.capeverde": "Cap-Vert",
      "team.afcon.car": "République centrafricaine",
      "team.afcon.chad": "Tchad",
      "team.afcon.comoros": "Comores",
      "team.afcon.congo": "Congo",
      "team.afcon.drcongo": "RD Congo",
      "team.afcon.cotedivoire": "Côte d’Ivoire",
      "team.afcon.djibouti": "Djibouti",
      "team.afcon.egypt": "Égypte",
      "team.afcon.equatorialguinea": "Guinée équatoriale",
      "team.afcon.eritrea": "Érythrée",
      "team.afcon.eswatini": "Eswatini",
      "team.afcon.ethiopia": "Éthiopie",
      "team.afcon.gabon": "Gabon",
      "team.afcon.gambia": "Gambie",
      "team.afcon.ghana": "Ghana",
      "team.afcon.guinea": "Guinée",
      "team.afcon.guineabissau": "Guinée-Bissau",
      "team.afcon.kenya": "Kenya",
      "team.afcon.lesotho": "Lesotho",
      "team.afcon.liberia": "Liberia",
      "team.afcon.libya": "Libye",
      "team.afcon.madagascar": "Madagascar",
      "team.afcon.malawi": "Malawi",
      "team.afcon.mali": "Mali",
      "team.afcon.mauritania": "Mauritanie",
      "team.afcon.mauritius": "Maurice",
      "team.afcon.morocco": "Maroc",
      "team.afcon.mozambique": "Mozambique",
      "team.afcon.namibia": "Namibie",
      "team.afcon.niger": "Niger",
      "team.afcon.nigeria": "Nigeria",
      "team.afcon.rwanda": "Rwanda",
      "team.afcon.saotome": "São Tomé-et-Príncipe",
      "team.afcon.senegal": "Sénégal",
      "team.afcon.seychelles": "Seychelles",
      "team.afcon.sierraleone": "Sierra Leone",
      "team.afcon.somalia": "Somalie",
      "team.afcon.southafrica": "Afrique du Sud",
      "team.afcon.southsudan": "Soudan du Sud",
      "team.afcon.sudan": "Soudan",
      "team.afcon.tanzania": "Tanzanie",
      "team.afcon.togo": "Togo",
      "team.afcon.tunisia": "Tunisie",
      "team.afcon.uganda": "Ouganda",
      "team.afcon.zambia": "Zambie",
      "team.afcon.zimbabwe": "Zimbabwe",
    },

    en: {
      // --- COMMON (missing keys you saw on Predictions) ---
      "common.matches": "Matches",
      "common.done": "Done",
      "common.cancel": "Cancel",
      "common.confirm": "Confirm",
      "common.prevAria": "Previous",
      "common.nextAria": "Next",
      "common.closeAria": "Close",
      "common.betPlus": "Predictions",
      "common.about": "About",
      "common.pointsLabel": "Points:",

      // --- RESULTS (generated by resultsPage.js) ---
      "league.laliga": "La Liga",
      "league.bundesliga": "Bundesliga",
      "league.premier": "Premier League",
      "league.afcon": "Afcon",
      "results.seasonTitle": "Season 2025 - 2026",
      "results.pointsLabel": "Points:",
      "results.guest": "Guest",
      "results.match": "MATCH",
      "results.yourPrediction": "Your prediction",
      "results.finalScore": "Final score",
      "results.noPredictions": "No predictions for {league} yet.",
      "results.noResultsYet": "No results yet.",

      // --- PREDICTIONS (generated by predictionsPage.js) ---
      "predictions.leagueMatches": "{league} Matches",
      "predictions.matchdayOf": "Matchday {n} of {total}",
      "predictions.ofTotalShort": "{n} of {total}",
      "predictions.confirmTitle":
        "Are you sure you want to submit these scores? Please confirm that all the information is correct.",
      "predictions.enterPredictionScore": "Enter your prediction score",
      "predictions.matchdayWord": "Matchday",
      "predictions.groupHeader": "{group} - Matchday {n}",

      // (Keep your old flat keys too in case some pages still use them)
      matches: "Matches",
      done: "Done",
      cancel: "Cancel",
      confirm: "Confirm",
      prevAria: "Previous",
      nextAria: "Next",
      closeAria: "Close",
      leagueMatches: "{league} Matches",
      matchdayOf: "Matchday {n} of {total}",
      ofTotalShort: "{n} of {total}",
      confirmTitle:
        "Are you sure you want to submit these scores? Please confirm that all the information is correct.",
      enterPredictionScore: "Enter your prediction score",
      matchdayWord: "Matchday",
      groupHeader: "{group} - Matchday {n}",

      // ===== existing =====
      app_name: "FANSBETLIGA",
      about: "About",
      wallet: "Wallet",
      notifications: "Notifications",
      login: "Login",
      signup: "Sign up",
      email: "Email",
      password: "Password",
      confirm_password: "Confirm password",
      start: "Start",
      bet_plus: "Pronostics +",
      add_money: "Add money",
      withdraw_funds: "Withdraw funds",
      recent_transactions: "Recent Transactions",
      view_all: "View all",
      current_balance: "Current Balance",
      bonus_balance: "Bonus Balance",
      language: "Language",
      english: "English",
      french: "French",

      // ===== added (minimal) to match your CURRENT HTML keys =====
      "app.brand": "FANSBETLIGA",
      "nav.notificationsAria": "Notifications",
      "nav.notificationsAlt": "Notifications",

      "nav.home": "Home",
      "nav.results": "Results",
      "nav.winners": "Winners",
      "nav.rules": "Rules",

      "nav.notifications": "Notifications",
      "wallet.withdrawBonus": "Withdraw Bonus",
      "wallet.wallet": "Wallet",

      "afcon.groupA.heading": "AFCON 2025 — Group A",
      "afcon.groupB.heading": "AFCON 2025 — Group B",
      "afcon.groupC.heading": "AFCON 2025 — Group C",
      "afcon.groupD.heading": "AFCON 2025 — Group D",
      "afcon.groupE.heading": "AFCON 2025 — Group E",
      "afcon.groupF.heading": "AFCON 2025 — Group F",

      "afcon.groupA.tab": "Group A",
      "afcon.groupB.tab": "Group B",
      "afcon.groupC.tab": "Group C",
      "afcon.groupD.tab": "Group D",
      "afcon.groupE.tab": "Group E",
      "afcon.groupF.tab": "Group F",

      "afcon.groupA.day1.date": "Sunday, 21 Dec 2025",
      "afcon.groupA.day2.date": "Friday, 26 Dec 2025",
      "afcon.groupA.day3.date": "Tuesday, 29 Dec 2025",

      "afcon.groupB.day1.date": "Monday, 22 Dec 2025",
      "afcon.groupB.day2.date": "Friday, 26 Dec 2025",
      "afcon.groupB.day3.date": "Monday, 29 Dec 2025",

      "afcon.groupC.day1.date": "Tuesday, 23 Dec 2025",
      "afcon.groupC.day2.date": "Saturday, 27 Dec 2025",
      "afcon.groupC.day3.date": "Tuesday, 30 Dec 2025",

      "afcon.groupD.day1.date": "Tuesday, 23 Dec 2025",
      "afcon.groupD.day2.date": "Saturday, 27 Dec 2025",
      "afcon.groupD.day3.date": "Tuesday, 30 Dec 2025",

      "afcon.groupE.day1.date": "Wednesday, 24 Dec 2025",
      "afcon.groupE.day2.date": "Sunday, 28 Dec 2025",
      "afcon.groupE.day3.date": "Wednesday, 31 Dec 2025",

      "afcon.groupF.day1.date": "Wednesday, 24 Dec 2025",
      "afcon.groupF.day2.date": "Sunday, 28 Dec 2025",
      "afcon.groupF.day3.date": "Wednesday, 31 Dec 2025",

      // ✅ matchday headers MUST be FLAT keys (strings)
      "afcon.groupA.matchdayHeader": "Group A - Matchday {n} of {total}",
      "afcon.groupB.matchdayHeader": "Group B - Matchday {n} of {total}",
      "afcon.groupC.matchdayHeader": "Group C - Matchday {n} of {total}",
      "afcon.groupD.matchdayHeader": "Group D - Matchday {n} of {total}",
      "afcon.groupE.matchdayHeader": "Group E - Matchday {n} of {total}",
      "afcon.groupF.matchdayHeader": "Group F - Matchday {n} of {total}",

      // --- WINNERS (winners.html + winnersPage.js) ---
      "winners.preseasonTitle": "Preseason 2025 - 2026",
      "winners.classification": "CLASSIFICATION",

      "winners.dailyRankings": "Daily Rankings",
      "winners.firstRound": "First Round",
      "winners.overall": "Overall",

      "winners.loadingRankings": "Loading rankings…",
      "winners.noRankingsYet": "No rankings yet.",
      "winners.noRankingsThisMatchday": "No rankings yet for this matchday.",

      "winners.rank": "Rank",
      "winners.player": "Player",
      "winners.points": "Points",
      "winners.pointsCol": "Points",

      "winners.groupMatchdayLabel": "{group} · Matchday {n}",

      // --- WALLET (wallet.html) ---
      "wallet.brand": "FansWallet",
      "wallet.currentBalance": "Current Balance",
      "wallet.bonusBalance": "Bonus Balance",
      "wallet.quickActions": "Quick Actions",
      "wallet.addMoney": "Add money",
      "wallet.withdrawFunds": "Withdraw Funds",
      "wallet.recentTransactions": "Recent Transactions",
      "wallet.viewAll": "View All",
      "wallet.deposit": "Deposit",
      "wallet.withdrawal": "Withdrawal",

      // Deposit modal
      "wallet.depositModal.title": "Make a deposit",
      "wallet.depositModal.aria": "Make a deposit",
      "wallet.provider.momo": "MTN Mobile Money",
      "wallet.provider.orange": "Orange Money",
      "wallet.amountLabel": "Amount (FCFA)",
      "wallet.amountPlaceholder": "e.g. 5000",
      "wallet.phoneLabel": "Phone number",
      "wallet.phonePlaceholder": "e.g. 6XXXXXXXX",
      "wallet.depositBtn": "Deposit",
      "wallet.cancelBtn": "Cancel",
      "wallet.depositNote":
        "After you confirm, you will receive a payment prompt on your phone.",

      // Withdraw modal
      "wallet.withdrawModal.title": "Withdraw funds",
      "wallet.withdrawModal.aria": "Withdraw funds",
      "wallet.withdrawBtn": "Withdraw",
      "wallet.withdrawNote":
        "Withdrawals may take a few minutes depending on the operator.",
      "wallet.closeAria": "Close",

      // ============================================================
      // ✅ ADDED NOW: AFCON teams (French + English)
      // Use in HTML/JS as: data-i18n="team.afcon.<slug>"
      // ============================================================

      "team.afcon.algeria": "Algeria",
      "team.afcon.angola": "Angola",
      "team.afcon.benin": "Benin",
      "team.afcon.botswana": "Botswana",
      "team.afcon.burkinafaso": "Burkina Faso",
      "team.afcon.burundi": "Burundi",
      "team.afcon.cameroon": "Cameroon",
      "team.afcon.capeverde": "Cape Verde",
      "team.afcon.car": "Central African Republic",
      "team.afcon.chad": "Chad",
      "team.afcon.comoros": "Comoros",
      "team.afcon.congo": "Congo",
      "team.afcon.drcongo": "DR Congo",
      "team.afcon.cotedivoire": "Côte d’Ivoire",
      "team.afcon.djibouti": "Djibouti",
      "team.afcon.egypt": "Egypt",
      "team.afcon.eqguinea": "Equatorial Guinea",
      "team.afcon.eritrea": "Eritrea",
      "team.afcon.eswatini": "Eswatini",
      "team.afcon.ethiopia": "Ethiopia",
      "team.afcon.gabon": "Gabon",
      "team.afcon.gambia": "Gambia",
      "team.afcon.ghana": "Ghana",
      "team.afcon.guinea": "Guinea",
      "team.afcon.guineabissau": "Guinea-Bissau",
      "team.afcon.kenya": "Kenya",
      "team.afcon.lesotho": "Lesotho",
      "team.afcon.liberia": "Liberia",
      "team.afcon.libya": "Libya",
      "team.afcon.madagascar": "Madagascar",
      "team.afcon.malawi": "Malawi",
      "team.afcon.mali": "Mali",
      "team.afcon.mauritania": "Mauritania",
      "team.afcon.mauritius": "Mauritius",
      "team.afcon.morocco": "Morocco",
      "team.afcon.mozambique": "Mozambique",
      "team.afcon.namibia": "Namibia",
      "team.afcon.niger": "Niger",
      "team.afcon.nigeria": "Nigeria",
      "team.afcon.rwanda": "Rwanda",
      "team.afcon.saotome": "São Tomé and Príncipe",
      "team.afcon.senegal": "Senegal",
      "team.afcon.seychelles": "Seychelles",
      "team.afcon.sierraleone": "Sierra Leone",
      "team.afcon.somalia": "Somalia",
      "team.afcon.southafrica": "South Africa",
      "team.afcon.southsudan": "South Sudan",
      "team.afcon.sudan": "Sudan",
      "team.afcon.tanzania": "Tanzania",
      "team.afcon.togo": "Togo",
      "team.afcon.tunisia": "Tunisia",
      "team.afcon.uganda": "Uganda",
      "team.afcon.zambia": "Zambia",
      "team.afcon.zimbabwe": "Zimbabwe",
    },
  };

  function getLang() {
    const v = (localStorage.getItem(STORAGE_KEY) || "").toLowerCase();
    return v === "en" || v === "fr" ? v : DEFAULT_LANG;
  }

  function setLang(lang) {
    const safe = (lang || "").toLowerCase() === "en" ? "en" : "fr";
    localStorage.setItem(STORAGE_KEY, safe);
    applyLang(safe);
  }

  function t(lang, key, vars) {
    let str =
      (DICT[lang] && DICT[lang][key]) ||
      (DICT[DEFAULT_LANG] && DICT[DEFAULT_LANG][key]) ||
      key;

    if (vars && typeof str === "string") {
      Object.keys(vars).forEach((k) => {
        str = str.replaceAll(`{${k}}`, String(vars[k]));
      });
    }
    return str;
  }

  function parseVars(s) {
    const out = {};
    (s || "")
      .split(",")
      .map((x) => x.trim())
      .filter(Boolean)
      .forEach((pair) => {
        const [k, v] = pair.split(":").map((z) => (z || "").trim());
        if (k) out[k] = v;
      });
    return out;
  }

  function applyLang(lang) {
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.textContent = t(lang, key, vars);
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.setAttribute("placeholder", t(lang, key, vars));
    });

    document.querySelectorAll("[data-i18n-title]").forEach((el) => {
      const key = el.getAttribute("data-i18n-title");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.setAttribute("title", t(lang, key, vars));
    });

    const dd = document.getElementById("langSelect");
    if (dd) dd.value = lang;

    document.documentElement.lang = lang;
  }

  // expose globally (include t so JS files can translate too)
  window.FBL_I18N = { getLang, setLang, applyLang, t, DICT };

  // apply as soon as DOM is ready
  document.addEventListener("DOMContentLoaded", () => {
    applyLang(getLang());

    // wire dropdown if it exists on this page
    const dd = document.getElementById("langSelect");
    if (dd) {
      dd.value = getLang();
      dd.addEventListener("change", (e) => setLang(e.target.value));
    }
  });
})();
