(function () {
  const STORAGE_KEY = "FBL_LANG";
  const DEFAULT_LANG = "en";

  // ✅ Your dictionary (add more keys anytime)
  const DICT = {
    fr: {
      // ===== existing =====

      // --- COMMON (missing keys you saw on Predictions) ---
      "common.matches": "Matchs",
      "common.done": "Terminé",
      "common.cancel": "Annuler",
      "common.confirm": "Confirmer",
      "common.prevAria": "Précédent",
      "common.nextAria": "Suivant",
      "common.closeAria": "Fermer",
      "common.betPlus": "Pronostics +",
      "common.about": "À propos",
      "common.pointsLabel": "Points :",

      // --- RESULTS (generated by resultsPage.js) ---
      "league.laliga": "La Liga",
      "league.bundesliga": "Bundesliga",
      "league.premier": "Premier League",
      "league.afcon": "Afcon",
      "results.seasonTitle": "Saison 2025 - 2026",
      "results.pointsLabel": "Points:",
      "results.guest": "Invité",
      "results.match": "MATCH",
      "results.yourPrediction": "Votre pronostic",
      "results.finalScore": "Score final",
      "results.noPredictions": "Aucun pronostic pour {league} pour le moment.",
      "results.noResultsYet": "Aucun résultat pour le moment.",

      // --- PREDICTIONS (generated by predictionsPage.js) ---
      "predictions.leagueMatches": "Matchs {league}",
      "predictions.matchdayOf": "Journée {n} sur {total}",
      "predictions.ofTotalShort": "{n} sur {total}",
      "predictions.confirmTitle":
        "Voulez-vous vraiment envoyer ces scores ? Veuillez confirmer que toutes les informations sont correctes.",
      "predictions.enterPredictionScore": "Entrez votre score de pronostic",
      "predictions.matchdayWord": "Journée",
      "predictions.groupHeader": "{group} - Journée {n}",

      // (Keep your old flat keys too in case some pages still use them)
      matches: "Matchs",
      done: "Terminé",
      cancel: "Annuler",
      confirm: "Confirmer",
      prevAria: "Précédent",
      nextAria: "Suivant",
      closeAria: "Fermer",
      leagueMatches: "Matchs {league}",
      matchdayOf: "Journée {n} sur {total}",
      ofTotalShort: "{n} sur {total}",
      confirmTitle:
        "Voulez-vous vraiment envoyer ces scores ? Veuillez confirmer que toutes les informations sont correctes.",
      enterPredictionScore: "Entrez votre score de pronostic",
      matchdayWord: "Journée",
      groupHeader: "{group} - Journée {n}",

      // ===== existing =====
      app_name: "FANSBETLIGA",
      about: "À propos",
      wallet: "Portefeuille",
      notifications: "Notifications",
      login: "Connexion",
      signup: "Inscription",
      email: "Email",
      password: "Mot de passe",
      confirm_password: "Confirmer le mot de passe",
      start: "Commencer",
      bet_plus: "Ponostiq",
      add_money: "Ajouter de l'argent",
      withdraw_funds: "Retirer des fonds",
      recent_transactions: "Transactions récentes",
      view_all: "Tout voir",
      current_balance: "Solde courant",
      bonus_balance: "Solde bonus",
      language: "Langue",
      english: "Anglais",
      french: "Français",

      // ===== added (minimal) to match your CURRENT HTML keys =====
      "app.brand": "FANSBETLIGA",
      "nav.notificationsAria": "Notifications",
      "nav.notificationsAlt": "Notifications",

      "nav.home": "Accueil",
      "nav.results": "Résultats",
      "nav.winners": "Gagnants",
      "nav.rules": "Règles",

      "nav.notifications": "Notifications",
      "wallet.withdrawBonus": "Retirer le bonus",
      "wallet.wallet": "Portefeuille",

      "predictions.matchStartedMsg": "Match commencé",
      "predictions.matchPassedMsg": "Match terminé",
      "predictions.matchLockedSaveMsg": "Sauvegarde verrouillée",
      // AFCON groups
      "afcon.groupA.heading": "CAN 2025 — Groupe A",
      "afcon.groupB.heading": "CAN 2025 — Groupe B",
      "afcon.groupC.heading": "CAN 2025 — Groupe C",
      "afcon.groupD.heading": "CAN 2025 — Groupe D",
      "afcon.groupE.heading": "CAN 2025 — Groupe E",
      "afcon.groupF.heading": "CAN 2025 — Groupe F",
       // AFCON
"afcon.quarterfinal.tab": "Quarts de finale",
"afcon.quarterfinal.title": "Quarts de finale",
"afcon.semifinal.tab": "Demi-finales",
      "afcon.groupA.tab": "Groupe A",
      "afcon.groupB.tab": "Groupe B",
      "afcon.groupC.tab": "Groupe C",
      "afcon.groupD.tab": "Groupe D",
      "afcon.groupE.tab": "Groupe E",
      "afcon.groupF.tab": "Groupe F",
      "afcon.round16.tab": "8es de finale",
      "afcon.round16.heading": "CAN 2025 — 8es de finale",
      "afcon.round16.title": "FansBetLiga — CAN 8es de finale",
      "afcon.round16.matchdayHeader": "8es de finale",
      "afcon.round16.day1.date": "8es de finale",
      "afcon.quarterfinal.heading": "CAN 2025 — Quarts de finale",
      "afcon.final.tab": "Finale",
      "afcon.thirdplace.tab": "Match pour la 3e place",
      

      "afcon.groupA.day1.date": "Dimache, 21 Déc 2025",
      "afcon.groupA.day2.date": "Vendredi, 26 Déc 2025",
      "afcon.groupA.day3.date": "Mardi, 29 Déc 2025",

      "afcon.groupB.day1.date": "Lundi, 22 Déc 2025",
      "afcon.groupB.day2.date": "Vendredi, 26 Déc 2025",
      "afcon.groupB.day3.date": "Lundi, 29 Déc 2025",

      "afcon.groupC.day1.date": "Mardi, 23 Déc 2025",
      "afcon.groupC.day2.date": "Samedi, 27 Déc 2025",
      "afcon.groupC.day3.date": "Mardi, 30 Déc 2025",

      "afcon.groupD.day1.date": "Mardi, 23 Déc 2025",
      "afcon.groupD.day2.date": "Samedi, 27 Déc 2025",
      "afcon.groupD.day3.date": "Mardi, 30 Déc 2025",

      "afcon.groupE.day1.date": "Mecredi, 24 Déc 2025",
      "afcon.groupE.day2.date": "Dimache, 28 Déc 2025",
      "afcon.groupE.day3.date": "Mercredi, 31 Déc 2025",

      "afcon.groupF.day1.date": "Mecredi, 24 Déc 2025",
      "afcon.groupF.day2.date": "Dimache, 28 Déc 2025",
      "afcon.groupF.day3.date": "Mercredi, 31 Déc 2025",

      // ✅ matchday headers MUST be FLAT keys (strings)
      "afcon.groupA.matchdayHeader": "Groupe A - Journée {n} sur {total}",
      "afcon.groupB.matchdayHeader": "Groupe B - Journée {n} sur {total}",
      "afcon.groupC.matchdayHeader": "Groupe C - Journée {n} sur {total}",
      "afcon.groupD.matchdayHeader": "Groupe D - Journée {n} sur {total}",
      "afcon.groupE.matchdayHeader": "Groupe E - Journée {n} sur {total}",
      "afcon.groupF.matchdayHeader": "Groupe F - Journée {n} sur {total}",

      "afcon.predictions.badge": "Pronostics CAN",
      "afcon.predictions.matchdayShort": "",

      // --- WINNERS (winners.html + winnersPage.js) ---
      "winners.preseasonTitle": "Pré-saison 2025 - 2026",
      "winners.classification": "CLASSEMENT",

      "winners.dailyRankings": "Classement journalier",
      "winners.firstRound": "1er tour",
      "winners.overall": "Général",

      "winners.loadingRankings": "Chargement du classement…",
      "winners.noRankingsYet": "Pas de classement pour l'instant.",
      "winners.noRankingsThisMatchday": "Pas de classement pour cette journée.",

      "winners.rank": "Rang",
      "winners.player": "Joueur",
      "winners.points": "Points",
      "winners.pointsCol": "Points",

      "winners.groupMatchdayLabel": "{group} · Journée {n}",

      // --- WALLET (wallet.html) ---
      "wallet.brand": "FansWallet",
      "wallet.currentBalance": "Solde courant",
      "wallet.bonusBalance": "Solde bonus",
      "wallet.quickActions": "Actions rapides",
      "wallet.addMoney": "Ajouter de l'argent",
      "wallet.withdrawFunds": "Retirer des fonds",
      "wallet.recentTransactions": "Transactions récentes",
      "wallet.viewAll": "Tout voir",
      "wallet.deposit": "Dépôt",
      "wallet.withdrawal": "Retrait",
      "winners.matchdayLabel": "Journée {n}",

      // Deposit modal
      "wallet.depositModal.title": "Faire un dépôt",
      "wallet.depositModal.aria": "Faire un dépôt",
      "wallet.provider.momo": "MTN Mobile Money",
      "wallet.provider.orange": "Orange Money",
      "wallet.amountLabel": "Montant (FCFA)",
      "wallet.amountPlaceholder": "ex. 5000",
      "wallet.phoneLabel": "Numéro de téléphone",
      "wallet.phonePlaceholder": "ex. 6XXXXXXXX",
      "wallet.depositBtn": "Dépôt",
      "wallet.cancelBtn": "Annuler",
      "wallet.depositNote":
        "Après confirmation, vous recevrez une demande de paiement sur votre téléphone.",

      // Withdraw modal
      "wallet.withdrawModal.title": "Retirer des fonds",
      "wallet.withdrawModal.aria": "Retirer des fonds",
      "wallet.withdrawBtn": "Retirer",
      "wallet.withdrawNote":
        "Les retraits peuvent prendre quelques minutes selon l’opérateur.",
      "wallet.closeAria": "Fermer",

      // ============================================================
      // ✅ ADDED NOW: AFCON teams (French + English)
      // Use in HTML/JS as: data-i18n="team.afcon.<slug>"
      // ============================================================

      "team.afcon.algeria": "Algérie",
      "team.afcon.angola": "Angola",
      "team.afcon.benin": "Bénin",
      "team.afcon.botswana": "Botswana",
      "team.afcon.burkinafaso": "Burkina Faso",
      "team.afcon.burundi": "Burundi",
      "team.afcon.cameroon": "Cameroun",
      "team.afcon.capeverde": "Cap-Vert",
      "team.afcon.car": "République centrafricaine",
      "team.afcon.chad": "Tchad",
      "team.afcon.comoros": "Comores",
      "team.afcon.congo": "Congo",
      "team.afcon.drcongo": "RD Congo",
      "team.afcon.cotedivoire": "Côte d’Ivoire",
      "team.afcon.djibouti": "Djibouti",
      "team.afcon.egypt": "Égypte",
      "team.afcon.equatorialguinea": "Guinée équatoriale",
      "team.afcon.eritrea": "Érythrée",
      "team.afcon.eswatini": "Eswatini",
      "team.afcon.ethiopia": "Éthiopie",
      "team.afcon.gabon": "Gabon",
      "team.afcon.gambia": "Gambie",
      "team.afcon.ghana": "Ghana",
      "team.afcon.guinea": "Guinée",
      "team.afcon.guineabissau": "Guinée-Bissau",
      "team.afcon.kenya": "Kenya",
      "team.afcon.lesotho": "Lesotho",
      "team.afcon.liberia": "Liberia",
      "team.afcon.libya": "Libye",
      "team.afcon.madagascar": "Madagascar",
      "team.afcon.malawi": "Malawi",
      "team.afcon.mali": "Mali",
      "team.afcon.mauritania": "Mauritanie",
      "team.afcon.mauritius": "Maurice",
      "team.afcon.morocco": "Maroc",
      "team.afcon.mozambique": "Mozambique",
      "team.afcon.namibia": "Namibie",
      "team.afcon.niger": "Niger",
      "team.afcon.nigeria": "Nigeria",
      "team.afcon.rwanda": "Rwanda",
      "team.afcon.saotome": "São Tomé-et-Príncipe",
      "team.afcon.senegal": "Sénégal",
      "team.afcon.seychelles": "Seychelles",
      "team.afcon.sierraleone": "Sierra Leone",
      "team.afcon.somalia": "Somalie",
      "team.afcon.southafrica": "Afrique du Sud",
      "team.afcon.southsudan": "Soudan du Sud",
      "team.afcon.sudan": "Soudan",
      "team.afcon.tanzania": "Tanzanie",
      "team.afcon.togo": "Togo",
      "team.afcon.tunisia": "Tunisie",
      "team.afcon.uganda": "Ouganda",
      "team.afcon.zambia": "Zambie",
      "team.afcon.zimbabwe": "Zimbabwe",

            // --- ABOUT (about.html) ---
      "about.title": "COMMENT JOUER À FansBetLiga ?",

      "about.section.howToPlay": `1- Choisis une ligue ; Actuellement (Première League, Série A, Liga, Bundesliga, Ligue1) Bientôt ;
a- International (Coupe du Monde, coupe d´europe, coupe d´Afrique des nations, Copa America, coupe d´asie des nations, championsleague)
b- Europe (Premiere League, SerieA, Liga, Bundesliga, Ligue1, Hollande, Portugual, Turkie, Belgique, Russie, etc.)
c- Afrique (Egypte, Maroc, Algerie, Afrique du Sud, Tunisie, Nigeria, RDC, Angola, Tanzanie, soudan, Cote d´ivoire, Cameroun, Senegal, Ghana…)
d- Amerique : (Bresil, Argentine, Mexique, Colombie, Uruguay, Equateur, Chili, Paraguay, Perou, Bolivie, Venezuela, Costa Rica, USA, Canada)
e- Asie (Arabie Saoudite, Japon, Coree du sud, Chine, Qatar, Australie, Iran, Emirats arabes unis, …)

N.B. Langues ; Anglais, Espagnol, arabe, chinois, japonais, coréen, turque, français, allemand, portugais, néerlandais etc.

2- Va sur Home, sélectionne-le Matchday (journée) et entre un score pour chaque Match (ex : 2-1)
3- Tu peux modifier tes scores jusqu´au coup d´envoi de chaque match. Dès que le match démarre, il est verrouillé.
Après avoir introduit les différents scores, tu appuis sur Pari (done) : tous tes scores de la journée s´affichent, tu vérifies puis tu confirmes.
Si tu es déjà inscris, les différents matchs (Jour, heure) avec tes scores s´affichent.
Si tu n´es pas encore inscris le système te demande de t´inscrire (3 possibilités au choix : Email, Google ou Facebook)
4- Quand les résultats officiels tombent, tes points sont calculés et visibles dans Results (Par Match et Total) — chaque fan de foot peut aller jusqu´à ce point sans payer de licences.
5- Par contre pour consulter le classement dans Winners : Daily (par Journée), First Round (phase aller), Over all (toute la saison) il faut payer sa licence (elle coutera 20€ en Europe et 20$ dans les autres continents).
Le fan qui clique sur Winner et qui n´a pas encore payé sa licence est redirigé vers le lien pour le faire.
Le payement peut se faire par Paypal, carte de crédit, transfert d´argent mobile par téléphone etc.
Dès que ce processus est validé et terminé, le fan peut voir son classement (49 positions : 24 avant le fan et 24 après lui).`,

      "about.section.howMuchWin": `HOW MUCH CAN THE TOP 10, ……WIN AFTER EACH MATCH DAY or AT THE END OF THE LEAGUE.

Pour les raisons de simplifications la mise par Journée sera de 5€ par fan. Pour une ligue ayant :
1.000 licenciés -> 5.000€
10.000 licenciés -> 50.000€
100.000 licenciés -> 500.000€
1.000.000 licenciés -> 5.000.000€

Nous devons encore définir si cette manne doit être repartis seulement entre les 3 premiers, ou entre les 10 premiers etc.

On pourrait :
- ≤ 1000 licenciés : Récompenser entre 3 et 10 personnes
- 1000 < licenciés ≤ 10.000 : récompenser entre 50 et 100
- 10.000 < licenciés ≤ 100.000 : récompenser entre 100 et 500
- 100.000 < licenciés ≤ 1.000.000 : récompenser entre 500 et 1000

Si parmi les fans (parieurs) occupant les 3 premières positions, il y en a qui n´ont pas misés :
- Ils recevront des attestations de vainqueurs + cadeaux (sponsors / FansBetLiga)
- Ceux qui ont misés recevront aussi ces cadeaux + leurs récompenses financières
La répartition exacte est affichée sur la page de la Journée (encart “prizes”) lorsque les récompenses sont actives.`,

      "about.section.getPrize": `HOW DO I GET MY PRIZE.

Si tu es gagnant d´une journée ou de tout le championnat :
- La récompense est directement créditée sur ton compte Fan sur la plateforme.
- Tu peux demander un retrait vers PayPal, OM/MOMO ou carte de crédit (compte bancaire).
- Les cadeaux en nature sont envoyés par la poste après échange par email (tu fournis ton adresse).`,

      "about.section.scoring": `HOW IS FansBetLiga scored ?

Simple et transparent.

Notes :
- Les points d´un Match ne sont calculés que si (a) tu as fait une prédiction avant le coup d´envoi et (b) un résultat officiel existe.
- Les points sont enregistrés par ligue, journée et saison.
- En cas d´égalité au classement, la récompense correspondante est partagée au ex æquo.`,

      "about.section.register": `HOW DO I REGISTER TO PLAY?

- Va sur Sign Up et crée un compte avec Nom, Email, mot de passe
- Tu peux aussi utiliser Google/Facebook si l´option social login est disponible
- Après l´inscription, tu es connecté et prêt à jouer.

N.B : on pourrait préciser ici comment créer son portemonnaie (recharge par Mobile Money, Paypal, carte, etc.) pour payer licence/mises et recevoir les récompenses.`,

      "about.section.age": `HOW OLD MUST I BE, TO PLAY?

- Tu dois avoir au moins 18 ans (ou l´âge légal applicable dans ton pays) si tu peux miser et gagner de l´argent.
- N.B : tu peux jouer comme fan, juste pour le fun, à partir de 15 ans (sans récompense financière).`,

      "about.section.deadlines": `WHEN MUST I ENTER BY?

- Par Match : jusqu´au coup d´envoi officiel (l´entrée se verrouille à l´heure du début)
- Par Journée : chaque match a son propre verrou. Si la journée commence à 14:00, tu peux encore prédire les matchs de 17:30 tant qu´ils ne sont pas commencés.

Conseil : valider au même moment pour éviter d´oublier certains matchs.`,

      "about.section.edit": `CAN I EDIT MY ENTRY?

Oui, autant de fois que tu veux tant que le Match n´a pas démarré.
Une fois le Match en statut “Live/started/finished”, le champ est désactivé et ta dernière prédiction sauvegardée fait foi.`,

      "about.section.leaderboard": `HOW DOES THE LEADERBOARD WORK?

- Daily : total des points sur une journée pour une ligue
- First Round : cumul des points sur la phase aller (si configurée)
- Overall : cumul des points sur toute la saison

Les classements se mettent à jour après réception et validation des résultats.`,

      "about.section.winners": `WHEN ARE WINNERS NOTIFIED?

Sous 72 heures après la validation officielle des résultats de la journée (délais possibles si report/annulation).
Les gagnants sont contactés par Email après avoir déjà vu leur résultat sur la plateforme.

WHAT ARE WINNER´S RESPONSABILITIES?
- Répondre à l´email sous 7 jours
- Fournir les justificatifs (âge/identité) si demandés
- Respecter les modalités du lot (délais, adresse, etc.)
L´absence de réponse peut entraîner la perte du lot.`,

      "about.section.cancellation": `WHAT HAPPENS IF A MATCH IS POSTPONED; ABANDONED OR CANCELLED?

- Postponed/rescheduled : ta prediction reste valide et sera notée dès que le résultat officiel est publié.
- Abandoned : si la ligue publie un résultat officiel, on l´utilise ; sinon, pas de points jusqu´à décision.
- Cancelled/not played : pas de résultat = pas de points.

Les décisions suivent les sources officielles de la ligue.`,

      "about.section.whatIs": `C´EST QUOI FANSBETLIGA?

- La plateforme qui unit les fans de foot à travers le monde entier en leur permettant de jouer sur le championnat de leur choix et de gagner un trophée en fin de saison.
- La plateforme qui organise la mise et la répartition des gains entre fans (parieurs).
- La plateforme qui inclut et célèbre les fans de football.
- La plateforme qui permet aux groupes (associations, entreprises, écoles/salles de classe etc.) de créer leur championnat privé.` ,
"afcon.round16.header": "AFCON — 8es de finale"
    },
   

    
    en: {
             // --- ABOUT (about.html) ---
      "about.title": "HOW TO PLAY FansBetLiga?",

      "about.section.howToPlay": `1) Choose a league. Currently: (Premier League, Serie A, La Liga, Bundesliga, Ligue 1). Coming soon:
a) International (World Cup, Euro, AFCON, Copa America, Asian Cup, Champions League)
b) Europe (Premier League, Serie A, La Liga, Bundesliga, Ligue 1, Netherlands, Portugal, Turkey, Belgium, Russia, etc.)
c) Africa (Egypt, Morocco, Algeria, South Africa, Tunisia, Nigeria, DR Congo, Angola, Tanzania, Sudan, Côte d’Ivoire, Cameroon, Senegal, Ghana…)
d) Americas (Brazil, Argentina, Mexico, Colombia, Uruguay, Ecuador, Chile, Paraguay, Peru, Bolivia, Venezuela, Costa Rica, USA, Canada)
e) Asia (Saudi Arabia, Japan, South Korea, China, Qatar, Australia, Iran, UAE, …)

Note: Languages: English, Spanish, Arabic, Chinese, Japanese, Korean, Turkish, French, German, Portuguese, Dutch, etc.

2) Go to Home, select the Matchday, and enter a score for each match (e.g., 2–1).
3) You can edit your scores until each match kicks off. Once the match starts, it is locked.
After entering all scores, tap “Done”: your matchday scores will appear for review, then you confirm.
If you are already registered, the matches (day/time) and your scores are shown.
If you are not registered yet, the system asks you to sign up (Email, Google, or Facebook).
4) When official results arrive, your points are calculated and visible in Results (per match and total). Up to this point, fans can play without paying for a license.
5) To view rankings in Winners (Daily, First Round, Overall), you must pay a license (20€ in Europe, 20$ elsewhere).
If you click Winners without a license, you are redirected to payment.
Payment can be via PayPal, credit card, or mobile money.
After payment is validated, you can see your ranking (49 positions: 24 above you and 24 below you).`,

      "about.section.howMuchWin": `HOW MUCH CAN THE TOP 10 WIN PER MATCHDAY OR AT THE END OF THE LEAGUE?

For simplicity, the matchday stake is 5€ per fan. For a league with:
1,000 licensed fans → 5,000€
10,000 licensed fans → 50,000€
100,000 licensed fans → 500,000€
1,000,000 licensed fans → 5,000,000€

We still need to define whether this pool is shared among the top 3 only, top 10, etc.

Possible approach:
- ≤ 1,000 licensed: reward 3 to 10 people
- 1,000 < licensed ≤ 10,000: reward 50 to 100
- 10,000 < licensed ≤ 100,000: reward 100 to 500
- 100,000 < licensed ≤ 1,000,000: reward 500 to 1,000

If some fans in the top 3 did not place a stake:
- They receive winner certificates + sponsor/FansBetLiga gifts
- Fans who staked receive gifts + cash rewards
Exact distribution appears on the Matchday page (“prizes”) when rewards are active.`,

      "about.section.getPrize": `HOW DO I GET MY PRIZE?

If you win a matchday or the full league:
- Your reward is credited directly to your FansBetLiga account balance.
- You can request a withdrawal to PayPal, Mobile Money, or a bank card/bank account.
- Physical gifts from sponsors/FansBetLiga are shipped after an email exchange (you provide your postal address).`,

      "about.section.scoring": `HOW IS FansBetLiga SCORED?

Simple and transparent.

Notes:
- Match points are calculated only if (a) you predicted before kickoff and (b) an official result exists.
- Points are recorded by league, matchday, and season.
- If players tie on the leaderboard, the corresponding reward is shared equally.`,

      "about.section.register": `HOW DO I REGISTER TO PLAY?

- Go to Sign Up and create an account (Name, Email, Password)
- You can also use Google/Facebook if social login is available
- After signing up, you are logged in and ready to play

Note: later we can add a wallet setup section (top up via Mobile Money/PayPal/card, used to pay license and stakes, and to receive rewards).`,

      "about.section.age": `HOW OLD MUST I BE TO PLAY?

- You must be at least 18 (or the legal age in your country) if you can stake money and win money back.
- Note: you can still play as a fan “for fun” from age 15 (without financial rewards).`,

      "about.section.deadlines": `WHEN MUST I ENTER MY SCORES?

- Per match: until official kickoff (entry locks at start time)
- Per matchday: each match has its own lock. If the matchday starts at 14:00, you can still predict matches at 17:30 as long as they haven’t started.

Tip: validate all predictions at the same time to avoid forgetting a match.`,

      "about.section.edit": `CAN I EDIT MY ENTRY?

Yes — as many times as you want until the match starts.
Once the match status is Live/started/finished, the field is disabled and your last saved prediction counts.`,

      "about.section.leaderboard": `HOW DOES THE LEADERBOARD WORK?

- Daily: total points on one matchday for a league
- First Round: total points for the first phase (if enabled)
- Overall: total points for the full season

Leaderboards update after results are received and validated.`,

      "about.section.winners": `WHEN ARE WINNERS NOTIFIED?

Within 72 hours after official validation of matchday results (delays may occur if matches are postponed/cancelled).
Winners are contacted by email after they can already see their results on the platform.

WINNER RESPONSIBILITIES:
- Reply to the email within 7 days
- Provide documents (age/identity) if requested
- Respect prize conditions (deadlines, delivery address, etc.)
No reply may result in losing the prize.`,

      "about.section.cancellation": `WHAT IF A MATCH IS POSTPONED, ABANDONED, OR CANCELLED?

- Postponed/rescheduled: your prediction remains valid and will be scored when the official result is published.
- Abandoned: if the league publishes an official result, we use it; otherwise no points until a decision is made.
- Cancelled/not played: no result = no points.

Decisions follow official league sources.`,

      "about.section.whatIs": `WHAT IS FANSBETLIGA?

- A platform that unites football fans worldwide, letting them play on their chosen league and win a trophy at the end of the season.
- A platform that manages stakes and the distribution of winnings among fans.
- A platform that includes and celebrates football fans.
- A platform that lets groups (associations, companies, schools/classrooms, etc.) create private prediction leagues.` ,



      // --- COMMON (missing keys you saw on Predictions) ---
      "common.matches": "Matches",
      "common.done": "Done",
      "common.cancel": "Cancel",
      "common.confirm": "Confirm",
      "common.prevAria": "Previous",
      "common.nextAria": "Next",
      "common.closeAria": "Close",
      "common.betPlus": "Predictions",
      "common.about": "About",
      "common.pointsLabel": "Points:",
      "winners.matchdayLabel": "Matchday {n}",
     
      // --- RESULTS (generated by resultsPage.js) ---
      "league.laliga": "La Liga",
      "league.bundesliga": "Bundesliga",
      "league.premier": "Premier League",
      "league.afcon": "Afcon",
      "results.seasonTitle": "Season 2025 - 2026",
      "results.pointsLabel": "Points:",
      "results.guest": "Guest",
      "results.match": "MATCH",
      "results.yourPrediction": "Your prediction",
      "results.finalScore": "Final score",
      "results.noPredictions": "No predictions for {league} yet.",
      "results.noResultsYet": "No results yet.",
      "afcon.round16.header": "AFCON — Round of 16",
      // --- PREDICTIONS (generated by predictionsPage.js) ---
      "predictions.leagueMatches": "{league} Matches",
      "predictions.matchdayOf": "Matchday {n} of {total}",
      "predictions.ofTotalShort": "{n} of {total}",
      "predictions.confirmTitle":
        "Are you sure you want to submit these scores? Please confirm that all the information is correct.",
      "predictions.enterPredictionScore": "Enter your prediction score",
      "predictions.matchdayWord": "Matchday",
      "predictions.groupHeader": "{group} - Matchday {n}",
       // AFCON
"afcon.quarterfinal.tab": "Quarter-finals",
"afcon.quarterfinal.title": "Quarter-finals",

      // (Keep your old flat keys too in case some pages still use them)
      matches: "Matches",
      done: "Done",
      cancel: "Cancel",
      confirm: "Confirm",
      prevAria: "Previous",
      nextAria: "Next",
      closeAria: "Close",
      leagueMatches: "{league} Matches",
      matchdayOf: "Matchday {n} of {total}",
      ofTotalShort: "{n} of {total}",
      confirmTitle:
        "Are you sure you want to submit these scores? Please confirm that all the information is correct.",
      enterPredictionScore: "Enter your prediction score",
      matchdayWord: "Matchday",
      groupHeader: "{group} - Matchday {n}",

      // ===== existing =====
      app_name: "FANSBETLIGA",
      about: "About",
      wallet: "Wallet",
      notifications: "Notifications",
      login: "Login",
      signup: "Sign up",
      email: "Email",
      password: "Password",
      confirm_password: "Confirm password",
      start: "Start",
      bet_plus: "Pronostics +",
      add_money: "Add money",
      withdraw_funds: "Withdraw funds",
      recent_transactions: "Recent Transactions",
      view_all: "View all",
      current_balance: "Current Balance",
      bonus_balance: "Bonus Balance",
      language: "Language",
      english: "English",
      french: "French",

      // ===== added (minimal) to match your CURRENT HTML keys =====
      "app.brand": "FANSBETLIGA",
      "nav.notificationsAria": "Notifications",
      "nav.notificationsAlt": "Notifications",

      "nav.home": "Home",
      "nav.results": "Results",
      "nav.winners": "Winners",
      "nav.rules": "Rules",

      "nav.notifications": "Notifications",
      "wallet.withdrawBonus": "Withdraw Bonus",
      "wallet.wallet": "Wallet",

      "afcon.groupA.heading": "AFCON 2025 — Group A",
      "afcon.groupB.heading": "AFCON 2025 — Group B",
      "afcon.groupC.heading": "AFCON 2025 — Group C",
      "afcon.groupD.heading": "AFCON 2025 — Group D",
      "afcon.groupE.heading": "AFCON 2025 — Group E",
      "afcon.groupF.heading": "AFCON 2025 — Group F",

      "afcon.groupA.tab": "Group A",
      "afcon.groupB.tab": "Group B",
      "afcon.groupC.tab": "Group C",
      "afcon.groupD.tab": "Group D",
      "afcon.groupE.tab": "Group E",
      "afcon.groupF.tab": "Group F",
      "afcon.round16.tab": "Round of 16",
      "afcon.round16.heading": "AFCON 2025 — Round of 16",
      "afcon.round16.title": "FansBetLiga — AFCON Round of 16",
      "afcon.round16.matchdayHeader": "Round of 16",
      "afcon.round16.day1.date": "Round of 16",
       "afcon.semifinal.tab": "Semi-finals",
      "afcon.semifinal.title": "Semi-finals",
      "afcon.final.tab": "Final",
      "afcon.thirdplace.tab": "Match of 3rd Place",
      "afcon.groupA.day1.date": "Sunday, 21 Dec 2025",
      "afcon.groupA.day2.date": "Friday, 26 Dec 2025",
      "afcon.groupA.day3.date": "Tuesday, 29 Dec 2025",

      "afcon.groupB.day1.date": "Monday, 22 Dec 2025",
      "afcon.groupB.day2.date": "Friday, 26 Dec 2025",
      "afcon.groupB.day3.date": "Monday, 29 Dec 2025",

      "afcon.groupC.day1.date": "Tuesday, 23 Dec 2025",
      "afcon.groupC.day2.date": "Saturday, 27 Dec 2025",
      "afcon.groupC.day3.date": "Tuesday, 30 Dec 2025",

      "afcon.groupD.day1.date": "Tuesday, 23 Dec 2025",
      "afcon.groupD.day2.date": "Saturday, 27 Dec 2025",
      "afcon.groupD.day3.date": "Tuesday, 30 Dec 2025",

      "afcon.groupE.day1.date": "Wednesday, 24 Dec 2025",
      "afcon.groupE.day2.date": "Sunday, 28 Dec 2025",
      "afcon.groupE.day3.date": "Wednesday, 31 Dec 2025",

      "afcon.groupF.day1.date": "Wednesday, 24 Dec 2025",
      "afcon.groupF.day2.date": "Sunday, 28 Dec 2025",
      "afcon.groupF.day3.date": "Wednesday, 31 Dec 2025",
      "afcon.predictions.badge": "AFCON Predictions",
      "afcon.predictions.matchdayShort": "",

      // ✅ matchday headers MUST be FLAT keys (strings)
      "afcon.groupA.matchdayHeader": "Group A - Matchday {n} of {total}",
      "afcon.groupB.matchdayHeader": "Group B - Matchday {n} of {total}",
      "afcon.groupC.matchdayHeader": "Group C - Matchday {n} of {total}",
      "afcon.groupD.matchdayHeader": "Group D - Matchday {n} of {total}",
      "afcon.groupE.matchdayHeader": "Group E - Matchday {n} of {total}",
      "afcon.groupF.matchdayHeader": "Group F - Matchday {n} of {total}",

      // --- WINNERS (winners.html + winnersPage.js) ---
      "winners.preseasonTitle": "Preseason 2025 - 2026",
      "winners.classification": "CLASSIFICATION",

      "winners.dailyRankings": "Daily Rankings",
      "winners.firstRound": "First Round",
      "winners.overall": "Overall",

      "winners.loadingRankings": "Loading rankings…",
      "winners.noRankingsYet": "No rankings yet.",
      "winners.noRankingsThisMatchday": "No rankings yet for this matchday.",

      "winners.rank": "Rank",
      "winners.player": "Player",
      "winners.points": "Points",
      "winners.pointsCol": "Points",

      "winners.groupMatchdayLabel": "{group} · Matchday {n}",

      // --- WALLET (wallet.html) ---
      "wallet.brand": "FansWallet",
      "wallet.currentBalance": "Current Balance",
      "wallet.bonusBalance": "Bonus Balance",
      "wallet.quickActions": "Quick Actions",
      "wallet.addMoney": "Add money",
      "wallet.withdrawFunds": "Withdraw Funds",
      "wallet.recentTransactions": "Recent Transactions",
      "wallet.viewAll": "View All",
      "wallet.deposit": "Deposit",
      "wallet.withdrawal": "Withdrawal",

      // Deposit modal
      "wallet.depositModal.title": "Make a deposit",
      "wallet.depositModal.aria": "Make a deposit",
      "wallet.provider.momo": "MTN Mobile Money",
      "wallet.provider.orange": "Orange Money",
      "wallet.amountLabel": "Amount (FCFA)",
      "wallet.amountPlaceholder": "e.g. 5000",
      "wallet.phoneLabel": "Phone number",
      "wallet.phonePlaceholder": "e.g. 6XXXXXXXX",
      "wallet.depositBtn": "Deposit",
      "wallet.cancelBtn": "Cancel",
      "wallet.depositNote":
        "After you confirm, you will receive a payment prompt on your phone.",

      // Withdraw modal
      "wallet.withdrawModal.title": "Withdraw funds",
      "wallet.withdrawModal.aria": "Withdraw funds",
      "wallet.withdrawBtn": "Withdraw",
      "wallet.withdrawNote":
        "Withdrawals may take a few minutes depending on the operator.",
      "wallet.closeAria": "Close",

      // ============================================================
      // ✅ ADDED NOW: AFCON teams (French + English)
      // Use in HTML/JS as: data-i18n="team.afcon.<slug>"
      // ============================================================

      "team.afcon.algeria": "Algeria",
      "team.afcon.angola": "Angola",
      "team.afcon.benin": "Benin",
      "team.afcon.botswana": "Botswana",
      "team.afcon.burkinafaso": "Burkina Faso",
      "team.afcon.burundi": "Burundi",
      "team.afcon.cameroon": "Cameroon",
      "team.afcon.capeverde": "Cape Verde",
      "team.afcon.car": "Central African Republic",
      "team.afcon.chad": "Chad",
      "team.afcon.comoros": "Comoros",
      "team.afcon.congo": "Congo",
      "team.afcon.drcongo": "DR Congo",
      "team.afcon.cotedivoire": "Côte d’Ivoire",
      "team.afcon.djibouti": "Djibouti",
      "team.afcon.egypt": "Egypt",
      "team.afcon.equatorialguinea": "Equatorial Guinea",
      "team.afcon.eritrea": "Eritrea",
      "team.afcon.eswatini": "Eswatini",
      "team.afcon.ethiopia": "Ethiopia",
      "team.afcon.gabon": "Gabon",
      "team.afcon.gambia": "Gambia",
      "team.afcon.ghana": "Ghana",
      "team.afcon.guinea": "Guinea",
      "team.afcon.guineabissau": "Guinea-Bissau",
      "team.afcon.kenya": "Kenya",
      "team.afcon.lesotho": "Lesotho",
      "team.afcon.liberia": "Liberia",
      "team.afcon.libya": "Libya",
      "team.afcon.madagascar": "Madagascar",
      "team.afcon.malawi": "Malawi",
      "team.afcon.mali": "Mali",
      "team.afcon.mauritania": "Mauritania",
      "team.afcon.mauritius": "Mauritius",
      "team.afcon.morocco": "Morocco",
      "team.afcon.mozambique": "Mozambique",
      "team.afcon.namibia": "Namibia",
      "team.afcon.niger": "Niger",
      "team.afcon.nigeria": "Nigeria",
      "team.afcon.rwanda": "Rwanda",
      "team.afcon.saotome": "São Tomé and Príncipe",
      "team.afcon.senegal": "Senegal",
      "team.afcon.seychelles": "Seychelles",
      "team.afcon.sierraleone": "Sierra Leone",
      "team.afcon.somalia": "Somalia",
      "team.afcon.southafrica": "South Africa",
      "team.afcon.southsudan": "South Sudan",
      "team.afcon.sudan": "Sudan",
      "team.afcon.tanzania": "Tanzania",
      "team.afcon.togo": "Togo",
      "team.afcon.tunisia": "Tunisia",
      "team.afcon.uganda": "Uganda",
      "team.afcon.zambia": "Zambia",
      "team.afcon.zimbabwe": "Zimbabwe",
    },
  };

  function getLang() {
    const v = (localStorage.getItem(STORAGE_KEY) || "").toLowerCase();
    return v === "en" || v === "fr" ? v : DEFAULT_LANG;
  }

  function setLang(lang) {
    const safe = (lang || "").toLowerCase() === "en" ? "en" : "fr";
    localStorage.setItem(STORAGE_KEY, safe);
    applyLang(safe);
  }

  function t(lang, key, vars) {
    let str =
      (DICT[lang] && DICT[lang][key]) ||
      (DICT[DEFAULT_LANG] && DICT[DEFAULT_LANG][key]) ||
      key;

    if (vars && typeof str === "string") {
      Object.keys(vars).forEach((k) => {
        str = str.replaceAll(`{${k}}`, String(vars[k]));
      });
    }
    return str;
  }

  function parseVars(s) {
    const out = {};
    (s || "")
      .split(",")
      .map((x) => x.trim())
      .filter(Boolean)
      .forEach((pair) => {
        const [k, v] = pair.split(":").map((z) => (z || "").trim());
        if (k) out[k] = v;
      });
    return out;
  }

  function applyLang(lang) {
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.textContent = t(lang, key, vars);
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.setAttribute("placeholder", t(lang, key, vars));
    });

    document.querySelectorAll("[data-i18n-title]").forEach((el) => {
      const key = el.getAttribute("data-i18n-title");
      const vars = parseVars(el.getAttribute("data-i18n-vars"));
      el.setAttribute("title", t(lang, key, vars));
    });

    const dd = document.getElementById("langSelect");
    if (dd) dd.value = lang;

    document.documentElement.lang = lang;
  }

  // expose globally (include t so JS files can translate too)
  window.FBL_I18N = { getLang, setLang, applyLang, t, DICT };

  // apply as soon as DOM is ready
  document.addEventListener("DOMContentLoaded", () => {
    applyLang(getLang());

    // wire dropdown if it exists on this page
    const dd = document.getElementById("langSelect");
    if (dd) {
      dd.value = getLang();
      dd.addEventListener("change", (e) => setLang(e.target.value));
    }
  });
})();
